DROP TABLE cliente CASCADE CONSTRAINT;
DROP TABLE quarto CASCADE CONSTRAINT;
DROP TABLE produto CASCADE CONSTRAINT;
DROP TABLE funcionario CASCADE CONSTRAINT;
DROP TABLE telefoneCliente;
DROP TABLE hospedaQuartos;
DROP TABLE reservaQuarto;
DROP TABLE manutencao;
DROP TABLE dependente;
DROP TABLE avaliacao;
DROP TABLE vendaProdutos;
DROP TABLE equipamentos;